### ISSUE TITLE
%POST_META|duration% not working

### ISSUE THREAD

**Issue by markusk** [eteubert/archivist-custom-archive-templates#3]
Maybe I made a stupid error, but the above - and other %POST_META% placeholder is not working. Here is the code I used in the element part:
```HTML
<tr>
	<td>%POST_THUMBNAIL|50x50%</td>
	<td>
	    <a href="%PERMALINK%" class="permalink">%TITLE%</a><br/>
	</td>
    <td>%DATE%</td>
    <td>%POST_META|duration%</td>
</tr>
```
And here ist the result: http://www.robotiklabor.de/archiv/ (no date displayed). Any help appreciated...

**Comment by eteubert** [comment]
I see you're using the [Podcast Publisher](https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/). It doesn't write the duration into a meta field, so you can't access it via the `POST_META` tag.

Have you tried the `[podlove-episode-list]` shortcode?

**Comment by markusk** [comment]
Correct. Hm, I thought I had these meta data in the past... but anyway I completely missed the podlove-episode-list shortcode. Thanks for that!

And although I already know, that this is not the right place to ask: do you know how to change the headings to German?

**Comment by eteubert** [comment]
Not possible, you will have to use Templates.
But you can just take the template that is generating the shortcode and adjust it to your needs: http://docs.podlove.org/reference/templates/#list-of-episodes

**Comment by markusk** [comment]
Fair enough. I did not thought about that - although using templates already. :-)
Thanks for your support!
